[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "visitum_project"
version = "0.1.0" 

[tool.setuptools.packages.find]
where = ["src"] # Tell setuptools packages are under src